#!/usr/bin/env bash

echo "Generating Rosey base locale"
npx rosey generate --source dist

echo "Writing locales"
npx rcc-v2 write-locales --source rosey --locales fr,de

echo "Translating site with Rosey"
mv ./dist ./_untranslated_site
npx rosey build --source _untranslated_site --dest dist --default-language-at-root
